### ISSUE TITLE
Fatal error: "log" exists. Either use "--append" or (re)move it

### ISSUE THREAD

**Issue by arnydo** [TKCERT/testssl.sh-webfrontend#5]
When running the stock config with no previous runs/logs I receive this error.

Cleared out the log files, tried again and received the same error.

![image](https://cloud.githubusercontent.com/assets/11653079/26013354/f9cac3d2-3725-11e7-9079-ae39e73b3e13.png)

**Comment by thomaspatzke** [comment]
Perhaps the result of changed testssl.sh behaviour. Have to check this.

**Comment by arnydo** [comment]
I did see a few mentions of the mass scan mode on the latest testssl.sh updates. I will look into this more and see if that is what it was.

**Comment by thomaspatzke** [comment]
Just tested with supported testssl.sh version and it works. Update installation instructions accordingly to ensure that dependency is cloned as referenced by submodule.

Will update testssl.sh in the next weeks.

**Comment by arnydo** [comment]
Thank you!
