### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by vschurink** [TKCERT/testssl.sh-webfrontend#6]
Get the following error when trying to run it on my machine (ubuntu 16.04) 

  File "./SSLTestPortal.py", line 80, in main
    if not os.path.isdir(resultDirJSON):
NameError: name 'os' is not defined

Had to add "import os" to top of the SSLTestPortal.py file like so;

//
import os
from flask import Flask, request, redirect, session, render_template, url_for, flash
from os import urandom
from subprocess import Popen, PIPE, CalledProcessError, TimeoutExpired
import re
from datetime import datetime
import socket
//

**Comment by thomaspatzke** [comment]
Fixed in commit cb78121b3f713544e19f6aa8add0ec8bb7e8681f
