### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by KitchM** [TKCERT/testssl.sh-webfrontend#9]
"Configure SSLTestPortal.py, especially application.secret_key, in its configuration section and create the required paths (log, result/html and result/json in the default configuration)."

Would you mind please explaining that?  A little how-to goes a long way.

Thanks.

**Comment by KitchM** [comment]
Is the support closed for this app?

**Comment by thomaspatzke** [comment]
Hi! Sorry for answering so late, this project is currently not actively maintained.

To answer your questions:

* The variable *application.secret_key* is set to a random value by default. This causes that sessions get invalidated after restart of the application. Usually not a big deal for this application, but for a clean deployment you should set this to a static random value
* The directories configured in the application must exist. Elsewhere, results can't be written and it wouldn't work.
